@host = http://localhost:5164

GET {{host}}/api/animes
Accept: application/json

###

GET {{host}}/api/animes/1
Accept: application/json

###

GET {{host}}/api/animes/statistics
Accept: application/json

###

POST {{host}}/api/animes
Content-Type: application/json

{
  "title": "Steins;Gate",
  "genre": "Ciencia ficción y suspenso",
  "studio": "White Fox",
  "synopsis": "Un grupo de amigos descubre una forma de enviar mensajes al pasado.",
  "releaseYear": 2011,
  "episodes": 24,
  "rating": 9.0,
  "status": "Finished"
}

###

PUT {{host}}/api/animes/1
Content-Type: application/json

{
  "title": "Fullmetal Alchemist: Brotherhood",
  "genre": "Acción, aventura y fantasía",
  "studio": "Bones",
  "synopsis": "Dos hermanos alquimistas intentan recuperar lo que perdieron.",
  "releaseYear": 2009,
  "episodes": 64,
  "rating": 9.2,
  "status": "Finished"
}

###

DELETE {{host}}/api/animes/2
